<!DOCTYPE html>
<html lang="pt_BR">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Cadastrar Bovinos</title>

    <!-- Bootstrap core CSS -->
    <link href="<?php echo $_ENV['CUPIRAS_BASE']; ?>/assets/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="<?php echo $_ENV['CUPIRAS_BASE']; ?>/assets/css/dashboard.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
           <a href="/principal"><img src="../assets/images/logo-cupiras-br.png" /></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <form class="navbar-form navbar-right">
            <input class="form-control" type="text" class="form-control" placeholder="Buscar...">
          </form>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <h3>Proprietarios</h3>
          <ul class="nav nav-sidebar">
            <li><a href="#">Cadastrar</a></li>
            <li><a href="/proprietarios">Ver todos</a></li>
          </ul>
          <h3>Funcionários</h3>
          <ul class="nav nav-sidebar">
            <li><a href="/funcionarios/novo">Cadastrar</a></li>
            <li><a href="/funcionarios">Ver todos</a></li>
          </ul>
          <h3>Bovinos</h3>
          <ul class="nav nav-sidebar">
            <li class="active"><a href="/bovinos/novo">Cadastrar <span class="sr-only">(current)</span></a></li>
            <li><a href="/bovinos">Ver todos</a></li>
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <h2 class="page-header">Cadastrar Bovinos</h2>
          <div class="col-md-6">
			<form method="post" class="form">
				<div class="form-group">
					<label for="brinco">Brinco: </label>
					<input class="form-control" type="text" name="brinco" placeholder="Brinco" id="brinco" size="40">
				</div>
				<div class="form-group">
					<label for="datanascimento">Data Nascimento: </label>
					<input class="form-control" type="text" name="datanascimento" placeholder="Data Nascimento" id="datanascimento" size="40">
				</div>
				<div class="form-group">
					<label for="datavacina">Data Vacina: </label>
					<input class="form-control" type="text" name="datavacina" placeholder="Data Vacina" id="datavacina" size="40">
				</div>
				<div class="form-group">
					<label for="nome">Nome: </label>
					<input class="form-control" type="text" name="nome" placeholder="Nome" id="nome" size="40">
				</div>
				<div class="form-group">
					<label for="mae">Mãe: </label>
					<input class="form-control" type="text" name="mae" placeholder="Mãe" id="mae" size="40">
				</div>
				<div class="form-group">
					<label for="pai">Pai: </label>
					<input class="form-control" type="text" name="pai" placeholder="Pai" id="pai" size="40">
				</div>
				<div class="form-group">
					<label for="raca">Raça: </label>
					<input class="form-control" type="text" name="raca" placeholder="Raça" id="raca" size="40">
				</div>
				<input type="submit" name="enviar" value="Enviar" class="btn btn-lg btn-primary">
			</form>
		</div>
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="<?php echo $_ENV['CUPIRAS_BASE']; ?>/assets/js/bootstrap.min.js"></script>
    <script src="<?php echo $_ENV['CUPIRAS_BASE']; ?>/assets/js/dashboard.js"></script>
  </body>
</html>