<!DOCTYPE html>
<html lang="pt_BR">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Cadastrar Funcionarios</title>

    <!-- Bootstrap core CSS -->
    <link href="<?php echo $_ENV['CUPIRAS_BASE']; ?>/assets/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="<?php echo $_ENV['CUPIRAS_BASE']; ?>/assets/css/dashboard.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <form class="navbar-form navbar-right">
            <input class="form-control" type="text" class="form-control" placeholder="Buscar...">
          </form>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <h3>Proprietarios</h3>
          <ul class="nav nav-sidebar">
            <li><a href="#">Cadastrar</a></li>
            <li><a href="/proprietarios">Ver todos</a></li>
          </ul>
          <h3>Funcionários</h3>
          <ul class="nav nav-sidebar">
            <li class="active"><a href="/funcionarios/novo">Cadastrar <span class="sr-only">(current)</span></a></li>
            <li><a href="/funcionarios">Ver todos</a></li>
          </ul>
          <h3>Bovinos</h3>
          <ul class="nav nav-sidebar">
            <li><a href="/bovinos/novo">Cadastrar</a></li>
            <li><a href="/bovinos">Ver todos</a></li>
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <h2 class="page-header">Cadastrar Funcionarios</h2>
          <div class="col-md-6">
			<form method="post" class="form">
				<div class="form-group">
					<label for="nome">Nome: </label>
					<input class="form-control" type="text" name="nome" placeholder="Nome" id="nome" size="40">
				</div>
				<div class="form-group">
					<label for="rg">RG: </label>
					<input class="form-control" type="text" name="rg" placeholder="RG" id="rg" size="40">
				</div>
				<div class="form-group">
					<label for="cpf">CPF: </label>
					<input class="form-control" type="text" name="cpf" placeholder="CPF" id="cpf" size="40">
				</div>
				<div class="form-group">
					<label for="endereco">Endereço: </label>
					<input class="form-control" type="text" name="endereco" placeholder="Endereço" id="endereco" size="40">
				</div>
				<div class="form-group">
					<label for="contato">Contato: </label>
					<input class="form-control" type="text" name="contato" placeholder="Contato" id="contato" size="40">
				</div>
				<input type="submit" name="enviar" value="Enviar" class="btn btn-lg btn-primary">
			</form>
		</div>
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="<?php echo $_ENV['CUPIRAS_BASE']; ?>/assets/js/bootstrap.min.js"></script>
    <script src="<?php echo $_ENV['CUPIRAS_BASE']; ?>/assets/js/dashboard.js"></script>
  </body>
</html>