<!DOCTYPE html>
<html lang="en">
<head>
    <title>Tela Principal</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link type="text/css" href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,800italic,400,700,800">
    <link type="text/css" rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oswald:400,700,300">
    <link type="text/css" rel="stylesheet" href="/assets/styles/font-awesome.min.css">
    <link type="text/css" rel="stylesheet" href="/assets/styles/bootstrap.min.css">
    <link type="text/css" rel="stylesheet" href="/assets/styles/animate.css">
    <link type="text/css" rel="stylesheet" href="/assets/styles/all.css">
    <link type="text/css" rel="stylesheet" href="/assets/styles/main.css">
    <link type="text/css" rel="stylesheet" href="/assets/styles/style-responsive.css">
</head>
<body style="background: url('/assets/images/bg/bg.png') center center fixed;">
    <div class="container">
        <div class="col-md-12">
           
            <div class="logo">
                <img src="/assets/images/logo-cupiras.png" />
            </div>
          
            <div class="row">
              <ul>
                    <li class="col-lg-3"><a href="/proprietarios"><img src="/assets/images/icon1.png" /></a>Cadastrar Propietário</li>
                    <li class="col-lg-3"><a href="/funcionarios"><img src="/assets/images/icon2.png" /></a>Cadastrar Funcionário</li>
                    <li class="col-lg-3"><a href="/bovinos"><img src="/assets/images/icon3.png" /></a>Cadastrar Bovinos</li>
                    <li class="col-lg-3"><a href="#"><img src="/assets/images/icon4.png" /></a>Relatórios de Cadastro</li>
                </ul>
            </div>
      </div>
    </div>
</body>
</html>
