<!DOCTYPE html>
<html lang="en">
<head>
    <title>Cadastro de usuário</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link type="text/css" href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,800italic,400,700,800">
    <link type="text/css" rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oswald:400,700,300">
    <link type="text/css" rel="stylesheet" href="/assets/styles/font-awesome.min.css">
    <link type="text/css" rel="stylesheet" href="/assets/styles/bootstrap.min.css">
    <link type="text/css" rel="stylesheet" href="/assets/styles/animate.css">
    <link type="text/css" rel="stylesheet" href="/assets/styles/all.css">
    <link type="text/css" rel="stylesheet" href="/assets/styles/main.css">
    <link type="text/css" rel="stylesheet" href="/assets/styles/style-responsive.css">
</head>
<body style="background: url('/assets/images/bg/bg.png') center center fixed;">
    <div class="page-form">
        <div class="panel panel-blue">
            <div class="panel-body pan">
                <form action="/principal" class="form-horizontal">
                <div class="form-body pal">
                    <div class="col-md-12 text-center">
                        <h1 style="margin-top: -90px; font-size: 35px;">
                            Painel de Controle de Bovinos</h1>
                        <br />
                    </div>
                    <div class="form-group">
                        <div class="col-md-9">
                            <img src="/assets/images/logo-cupiras.png" style="margin-left:13%; margin-bottom:10px;" />
                            <br />    
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputName" class="col-md-2 control-label">
                           email:</label>
                        <div class="col-md-9">
                            <div class="input-icon right">
                                <i class="fa fa-user"></i>
                                <input id="inputName" type="text" placeholder="" class="form-control" /></div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputPassword" class="col-md-2 control-label">
                            Senha:</label>
                        <div class="col-md-9">
                            <div class="input-icon right">
                                <i class="fa fa-lock"></i>
                                <input id="inputPassword" type="text" placeholder="" class="form-control" /></div>
                        </div>
                    </div>
                    <div class="form-group mbn">
                        <div class="col-lg-12" align="right">
                            <div class="form-group mbn">
                                <div class="col-lg-2">
                                    &nbsp;
                                </div>
                                <div class="col-lg-9">
                                    <button type="submit" class="btn btn-default">
                                        Entrar</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                </form>
            </div>
        </div>
        <div class="col-lg-12 text-center">
            <p>
                <a href="#">Esqueceu sua senha CLIQUE AQUI ?</a>
            </p>
        </div>
    </div>
</body>
</html>
