<!DOCTYPE html>
<html lang="en">
<head>
    <title>Cadastro de usuário</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link type="text/css" href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,800italic,400,700,800">
    <link type="text/css" rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oswald:400,700,300">
    <link type="text/css" rel="stylesheet" href="<?php echo $_ENV["CUPIRAS_BASE"]; ?>/assets/styles/font-awesome.min.css">
    <link type="text/css" rel="stylesheet" href="<?php echo $_ENV["CUPIRAS_BASE"]; ?>/assets/styles/bootstrap.min.css">
    <link type="text/css" rel="stylesheet" href="<?php echo $_ENV["CUPIRAS_BASE"]; ?>/assets/styles/animate.css">
    <link type="text/css" rel="stylesheet" href="<?php echo $_ENV["CUPIRAS_BASE"]; ?>/assets/styles/all.css">
    <link type="text/css" rel="stylesheet" href="<?php echo $_ENV["CUPIRAS_BASE"]; ?>/assets/styles/main.css">
    <link type="text/css" rel="stylesheet" href="<?php echo $_ENV["CUPIRAS_BASE"]; ?>/assets/styles/style-responsive.css">
</head>
<body style="background: url('<?php echo $_ENV["CUPIRAS_BASE"]; ?>/assets/images/bg/bg.png') center center fixed;">
    <div class="page-form">
        <div class="panel panel-blue">
            <div class="panel-body pan">
                <form action="<?php echo $_ENV["CUPIRAS_BASE"]; ?>/login" class="form-horizontal" method="post">
                <div class="form-body pal">
                    <div class="col-md-12 text-center">
                        <h1 style="margin-top: -90px; font-size: 35px;">
                            Painel de Controle de Bovinos</h1>
                        <br />
                    </div>
                    <div class="form-group">
                        <div class="col-md-9">
                            <img src="<?php echo $_ENV["CUPIRAS_BASE"]; ?>/assets/images/logo-cupiras.png" style="margin-left:13%; margin-bottom:10px;" />
                            <br />    
                        </div>
                    </div>
                    <?php
				  		foreach ($flash->getMessages() as $message) {
				  			printf('<div style="border: 1px solid #000; background-color: #EE0000; margin: 5px; padding: 5px; color: #FFFFFF;"><p>%s</p></div>', $message);
				  		} 
				  	?>
                    <div class="form-group">
                        <label for="inputName" class="col-md-2 control-label">
                           email:</label>
                        <div class="col-md-9">
                            <div class="input-icon right">
                                <i class="fa fa-user"></i>
                                <input id="inputName" name="email" type="text" placeholder="E-mail" class="form-control" /></div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputPassword" class="col-md-2 control-label">
                            Senha:</label>
                        <div class="col-md-9">
                            <div class="input-icon right">
                                <i class="fa fa-lock"></i>
                                <input id="inputPassword" type="password" name="senha" placeholder="Senha" class="form-control" /></div>
                        </div>
                    </div>
                    <div class="form-group mbn">
                        <div class="col-lg-12" align="right">
                            <div class="form-group mbn">
                                <div class="col-lg-2">
                                    &nbsp;
                                </div>
                                <div class="col-lg-9">
                                    <button type="submit" class="btn btn-default">
                                        Entrar</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                </form>
            </div>
        </div>
        <div class="col-lg-12 text-center">
            <p>
                <a href="#">Esqueceu sua senha CLIQUE AQUI ?</a>
            </p>
        </div>
    </div>
</body>
</html>
